### ISSUE TITLE
TODO Add references to Digital Ecosystem

### ISSUE THREAD

**Issue by trbouma** [canada-ca/ucvdcc#7]
Need to Government of Canada section header with the following links

Directive on Identity Management (TBS Website)
Sign In Canada GitHub Repo
CATS-STAE GitHub Repo

**Comment by AdamPrins** [comment]
You can add the raw of this message. 
Sign In Canada has a number of repo's, and doesn't have one as a "main landing", so it just goes to the organization page.

## Government of Canada

1. [Directive on Identity Management](https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=16577)
2. [Sign In Canada GitHub Repo](https://github.com/sign-in-canada)
3. [CATS-STAE GitHub Repo](https://github.com/canada-ca/CATS-STAE)

**Comment by AdamPrins** [comment]
The above section was added to the ecosystem page. 
You may wish to rearrange its location (currently the bottom)
